### PR TITLE
.NET 6 Update

### PR DESCRIPTION
**Pull request by petervandenhout**
#106

### CODE REVIEW

**Comment by rywalters** [comment]
I get the following error when installing the metapackage:
NU1605	Detected package downgrade: Microsoft.EntityFrameworkCore.SqlServer from 6.0.1 to 6.0.0. Reference the package directly from the project to select a different version.

**Comment by petervandenhout** [comment]
@rywalters the Opw.PineBlog.EntityFrameworkCore package (https://www.nuget.org/packages/Opw.PineBlog.EntityFrameworkCore/) references:
```
[Microsoft.EntityFrameworkCore.InMemory](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.InMemory/) (>= 6.0.1)
[Microsoft.EntityFrameworkCore.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/) (>= 6.0.1)
[Microsoft.Extensions.Configuration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/) (>= 6.0.0)
```

So if you reference version `6.0.0` in one of your own projects it will preform a package downgrade for that package. You can solve it by referencing `6.0.1` in your projcts.
Hope that this helps

**Comment by rywalters** [comment]
Thanks for that! I'm trying not to be too much bother. To use program.cs instead of startup.cs in .NET 6, how would the code differ from what's in readme.md?

**Comment by petervandenhout** [comment]
@rywalters I haven't looked into that yet, but maybe this blog post will help you: [Upgrading a .NET 5 "Startup-based" app to .NET 6](https://andrewlock.net/exploring-dotnet-6-part-12-upgrading-a-dotnet-5-startup-based-app-to-dotnet-6/)

**Pull request merged**
